version: '2.1'

services:


 db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "dksdlfduq2"
      MYSQL_DATABASE: "mobiusdb"
    ports:
      - "3306:3306"
    network_mode: "host"
    volumes:
      - ./Mobius/sql:/docker-entrypoint-initdb.d
    healthcheck:
<<<<<<< HEAD
            test: ["CMD", "mysqladmin" ,"--password=dksdlfduq2","ping"]
            interval: 20s
=======
            test: ["CMD", "mysqladmin" , "--password=dksdlfduq2", "ping", "-h", "localhost"]
>>>>>>> 2674ab4b275ed08c33d94d1bd77968587654b3ab
            timeout: 20s
            retries: 5
 node:
    image: "node:7.6"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./Mobius:/home/node/app
    network_mode: "host"
    expose:
      - "8081"
    command: "node mobius"
    depends_on:
            db:
                condition: service_healthy
 mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    network_mode: "host"
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
    depends_on:
            db:
                condition: service_healthy
